# Generated by Django 3.2.7 on 2021-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select gender'), ('Male', 'Male'), ('Male', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lasname',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
