# Generated by Django 3.2.7 on 2021-09-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210923_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('module_code', models.CharField(blank=True, max_length=100, null=True)),
                ('module_credit', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'modules',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=70, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=70, null=True)),
                ('surname', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', 'select gender'), ('Male', 'Male'), ('Male', 'Female')], max_length=50, null=True)),
                ('contact', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=70, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=70, null=True)),
                ('dpt_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department')),
                ('programme_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.course')),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.module'),
        ),
    ]
