# Generated by Django 3.2.7 on 2021-09-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210923_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dpt_name',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
