# Generated by Django 3.2.7 on 2021-09-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210924_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.course'),
        ),
    ]
