# Generated by Django 3.2.7 on 2021-09-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_student_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'select status'), ('continous', 'continous'), ('postpone', 'postpone'), ('complete', 'complete')], max_length=50, null=True),
        ),
    ]
