# Generated by Django 3.2.7 on 2021-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20210924_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(blank=True, choices=[('continuous', 'continuous'), ('postpone', 'postpone'), ('complete', 'complete')], max_length=50, null=True),
        ),
    ]
