# Generated by Django 3.2.7 on 2021-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20210925_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='img_avatar.png', null=True, upload_to='media'),
        ),
    ]
