# Generated by Django 3.1.5 on 2021-09-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20210925_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_status',
        ),
    ]
