# Generated by Django 3.1.5 on 2021-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_student_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
    ]
