# Generated by Django 3.1.5 on 2021-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20210925_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
