# Generated by Django 3.1.5 on 2021-09-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_student_image'),
        ('account', '0037_auto_20210927_2018'),
    ]

    operations = [
    ]
