# Generated by Django 3.1.5 on 2021-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_merge_20210929_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'select gender'), ('Male', 'Male'), ('Male', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='img_avatar.png', upload_to='media'),
        ),
    ]
